DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS playlist_songs;
DROP TABLE IF EXISTS song;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE playlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  description TEXT,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);

CREATE TABLE playlist_songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  playlist_id INTEGER NOT NULL,
  added_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  song_id INTEGER NOT NULL,
  FOREIGN KEY (playlist_id) REFERENCES playlist (id),
  FOREIGN KEY (song_id) REFERENCES song (id)
);

CREATE TABLE song (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  source TEXT NOT NULL,
  url TEXT NOT NULL
);